visibility: hidden
project_urls:
    Bug Tracker: https://github.com/DragaDoncila/example-plugin/issues
    Documentation: https://github.com/DragaDoncila/example-plugin#README.md
    Source Code: https://github.com/DragaDoncila/example-plugin
    User Support: https://github.com/DragaDoncila/example-plugin/issues
