name: CI

on: 
  push:
    branches:
      - master
      - main
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:

  test:
    name: ${{ matrix.platform }} ${{ matrix.python-version }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9]
        include:
          - platform: windows-latest
            python-version: 3.8

    steps:
      - uses: actions/checkout@v2
      
      - name: napari hub Preview Page Builder
        uses: DragaDoncila/napari-hub-preview-action@v0.1.4
        with:
          hub-ref: main
